# -*- coding: utf-8 -*-
"""Thesyntaxsurgeon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILxAVvEKQtjrlPg9awvUgPLZxk0Ym_U7
"""

!pip install -q gradio transformers torch reportlab

# Import libraries
import gradio as gr
from transformers import pipeline
import torch
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# Model configuration
MODEL_NAME = "ibm-granite/granite-3.3-2b-instruct"

# Detect device
device = 0 if torch.cuda.is_available() else -1

# Load model
print("Loading IBM Granite Model...")
model = pipeline(
    "text-generation",
    model=MODEL_NAME,
    device=device
)
print("Model Loaded!")

# Chat history storage
chat_history = []

# Chat function
def chat(user_message, temperature, max_tokens, top_p):

    response = model(
        user_message,
        max_new_tokens=int(max_tokens),
        temperature=temperature,
        top_p=top_p,
        do_sample=True
    )

    answer = response[0]["generated_text"]

    chat_history.append(("User", user_message))
    chat_history.append(("AI", answer))

    history_text = ""
    for role, msg in chat_history:
        history_text += f"{role}: {msg}\n\n"

    return history_text

# Download TXT
def download_txt():

    filename = "chat_history.txt"

    with open(filename, "w") as f:
        for role, msg in chat_history:
            f.write(f"{role}: {msg}\n\n")

    return filename

# Download PDF
def download_pdf():

    filename = "chat_history.pdf"

    styles = getSampleStyleSheet()
    elements = []

    for role, msg in chat_history:
        elements.append(Paragraph(f"<b>{role}</b>: {msg}", styles["Normal"]))
        elements.append(Spacer(1,10))

    doc = SimpleDocTemplate(filename)
    doc.build(elements)

    return filename

# Clear chat
def clear_chat():
    global chat_history
    chat_history = []
    return ""

# UI using Gradio
with gr.Blocks(title="Granite Chatbot") as demo:

    gr.Markdown("# Granite Chatbot")
    gr.Markdown("Chat + Python Code Fixer - No API Keys")

    with gr.Row():

        # Chat section
        with gr.Column(scale=3):

            chat_box = gr.Textbox(
                label="Chat History",
                lines=20
            )

            user_input = gr.Textbox(
                label="Message"
            )

            send_btn = gr.Button("Send")

        # Control panel
        with gr.Column(scale=1):

            gr.Markdown("### Controls")

            clear_btn = gr.Button("Clear Chat")

            gr.Markdown("### Download")

            txt_btn = gr.Button("Download TXT")
            pdf_btn = gr.Button("Download PDF")

            txt_file = gr.File(label="TXT File")
            pdf_file = gr.File(label="PDF File")

    with gr.Row():

        temperature = gr.Slider(0,1,value=0.7,label="Temp")
        max_tokens = gr.Slider(50,512,value=256,label="Tokens")
        top_p = gr.Slider(0,1,value=0.95,label="Top-P")

    send_btn.click(
        chat,
        inputs=[user_input, temperature, max_tokens, top_p],
        outputs=chat_box
    )

    txt_btn.click(download_txt, outputs=txt_file)

    pdf_btn.click(download_pdf, outputs=pdf_file)

    clear_btn.click(clear_chat, outputs=chat_box)

demo.launch()